---
title: "R Notebook"
output: html_notebook
---

```{r}
# install.packages("sandwich")
# install.packages("lmtest")
# install.packages("aod")
# install.packages("dr4pl")
# install.packages("grid")
# install.packages("gridExtra")
# install.packages("lattice")
# install.packages("ggpubr")
# install.packages("ggplotify")
# install.packages("raster")
library(ggplotify)
library(dr4pl)
library(tidyverse)
library(sandwich)
library(lmtest)
library(drc)
library(tidymodels)
library(grid)
library(gridExtra)
library(lattice)
library(parsnip)
library(titanic)
library(aod)
library(ggpubr)
library(raster)
library(knitr)
library(patchwork)
```


Linear regression

```{r}
# create and summarise model
cars.model <- lm(dist ~ speed, data = cars)
summary(cars.model) 

# add 'fit', 'lwr', and 'upr' columns to dataframe (generated by predict)
cars.predict <- cbind(cars, predict(cars.model, interval = 'confidence'))

# plot the points (actual observations), regression line, and confidence interval
p <- ggplot(cars.predict, aes(speed,dist))
p <- p + geom_point()
p <- p + geom_line(aes(speed, fit))
p <- p + geom_ribbon(aes(ymin=lwr,ymax=upr), alpha=0.3)
p
```

4PL Logistic regression

```{r}

dr4pl.logistic.5 <- dr4pl(Response~Dose,
                            data = sample_data_5,
                            method.init = "logistic")

IC_data <- IC(dr4pl.logistic.5, c(10, 50, 90))

ex_or_inhib <- ifelse(IC_data %>% last > IC_data %>% first, "EC", "IC")

IC_EC_fix <- function(x) {
  paste0(ex_or_inhib, ifelse(ex_or_inhib == "IC", 
       100-as.numeric(str_extract(x, "[0-9]+")),
       as.numeric(str_extract(x, "[0-9]+"))))
}

IC_EC_fix("InhibPercent:90")

map_chr(c("InhibPercent:90", "InhibPercent:30"), ~IC_EC_fix(.x))

IC_table <- IC_data %>% 
  t() %>% 
  as_tibble() %>% 
  pivot_longer(cols = everything(), 
               names_to = "Response", 
               values_to = "Concentration") %>%
  mutate(Response = map_chr(Response, ~ IC_EC_fix(.x))) %>%
  tableGrob()

ggplot.logistic <- plot(dr4pl.logistic.5, text.title = "Logistic regression") +
  geom_vline(xintercept = IC_data, 
             linetype = "dashed", 
             color = "violetred3") +
  scale_y_continuous(labels = label_number_si())

ggplot.logistic + IC_table


```


Mead method

```{r}

dr4pl.Mead.5 <- dr4pl(Response~Dose,
                          data = sample_data_5)

ggplot.Mead <- plot(dr4pl.Mead.5, text.title = "Mead's method")

gridExtra::grid.arrange(ggplot.logistic, ggplot.Mead, nrow = 1, ncol = 2) 

dr4pl.3 <- dr4pl(Response ~ Dose, data = sample_data_3)

summary(dr4pl.3)




```


```{r}
x<-1:10

df<-data.frame(x)

ggplot(df,aes(x)) +
  stat_function(fun=dr4pl.logistic.5)


dd <- data.frame(dose = c(0.078125,0.156250,0.312500,0.625000,1.25,
                          2.50,5.0,10.0,20.0),
                 POC = c(1.05637425, 0.87380081, 0.79171200,
                         0.83166848, 0.77361290, 0.35199288,
                         0.19404609,  0.09079221, 0.09850658))

library(dr4pl)
ggplot(mtcars, aes(disp, qsec)) + geom_point() +
  geom_smooth(method="dr4pl",se=TRUE) #+ coord_trans(x="log10")

mtcars

library(ggplot2)

# install.packages('dplyr')
library(dplyr)

fit <- lm(dist ~ speed, data = cars)

cars %>%
  mutate( my_model = predict(fit) ) %>%
  ggplot() +
  geom_point( aes(speed, dist) ) +
  geom_line( aes(speed, my_model)  )



 






```

